[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:gunicorn]
command=gunicorn config.wsgi:application --config /app/deploy/gunicorn/gunicorn.conf.py
directory=/app
user=app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/gunicorn.log
environment=DJANGO_SETTINGS_MODULE="config.settings.production"
